language: ruby

before_install:
- gem install bundler
- pyenv install 2.7.8

script:
 - bundle exec rake test

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/feedvalidator
  
sudo: false # route your build to the container-based infrastructure for a faster build