language: generic

before_install:
- gem install bundler
- bundle install --jobs=3 --retry=3

script:
 - bundle exec rake test

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/feedvalidator-master
  
sudo: false # route your build to the container-based infrastructure for a faster build